[package]
name = "teleprobe-meta"
version = "1.1.0"
edition = "2021"
description = "Embed teleprobe metadata into ELF binaries"
repository = "https://github.com/embassy-rs/teleprobe"
license = "MIT OR Apache-2.0"
categories = [
    "embedded",
    "no-std",
]

[dependencies]
