name: ci
on:
  push:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install libusb, libudev (linux)
        run: |
          sudo apt update
          sudo apt install -y libusb-1.0-0-dev libudev-dev

      - name: Cache Dependencies
        uses: Swatinem/rust-cache@v1.3.0
        
      - uses: actions/checkout@v2
      - name: Build
        run: |
          cargo build
          cargo build --release
          cargo test
          cargo test --release
    