name: ci
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install libusb, libudev (linux)
        run: |
          sudo apt update
          sudo apt install -y libusb-1.0-0-dev libudev-dev

      - uses: actions/checkout@v4

      - name: Cache Dependencies
        uses: Swatinem/rust-cache@v1.3.0
        
      - name: Build
        run: |
          cargo build --manifest-path teleprobe/Cargo.toml
          cargo build --manifest-path teleprobe/Cargo.toml --release
          cargo test --manifest-path teleprobe/Cargo.toml
          cargo test --manifest-path teleprobe/Cargo.toml --release
      # - name: setup Rust
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2023-08-19
          targets: aarch64-unknown-linux-gnu

      - name: Install Cross
        uses: taiki-e/install-action@v2
        with:
          tool: cross

      - name: Cross-compile
        run: |
          cross build --target aarch64-unknown-linux-gnu